Librato:
  Enabled: true
  Email: 'colin@frozenorb.net'
  Token: '862219907e4a5fb7a919ac98e8db33bd8f9ea7074cf4dd354080ad716c7be948'
Redis:
  Host: 'localhost'
  DbId: 0
BackboneRedis:
  Host: '104.236.52.72'
  DbId: 0
UUIDCache:
  Backend: 'net.frozenorb.qlib.uuid.impl.RedisUUIDCache'
NametagPacketRestriction:
  Enabled: false
  BypassPrefix: '&a'
Command:
  TimeThreshold: 10
